[project]
name = "tree-sitter-mojo"
description = "Tree-Sitter of Mojolang"
version = "0.1.0"
keywords = ["incremental", "mojo", "parsing", "tree-sitter"]
classifiers = [
  "Intended Audience :: Developers",
  "Topic :: Software Development :: Compilers",
  "Topic :: Text Processing :: Linguistic",
  "Typing :: Typed",
]
authors = [{ name = "Aaron Ruan", email = "i@ar212.com" }]
requires-python = ">=3.10"
license.text = "MIT"
readme = "README.md"

[project.urls]
Funding = ""
Homepage = "https://github.com/aaron-212/tree-sitter-mojo"

[project.optional-dependencies]
core = ["tree-sitter~=0.24"]

[build-system]
requires = ["setuptools>=62.4.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp310-*"
build-frontend = "build"
