name: Test Tree-sitter Grammar

on:
  push:
    branches: main
  pull_request:

jobs:
  test:
    name: Test Tree-sitter Grammar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Setup Node
        uses: actions/setup-node@v6

      - name: Download Tree-sitter CLI
        run: npm install -g tree-sitter-cli

      - name: Verify Tree-sitter CLI
        run: tree-sitter --version

      - name: Test
        run: tree-sitter test
